# internal
APP_ID: bytes
AUTH_CODE: int

# Message
def sendPrivateMsg(auth_code: int, qq: int, msg: bytes) -> int: ...
def sendGroupMsg(auth_code: int,group_id:int,msg:bytes) -> int: ...
def sendDiscussMsg(auth_code: int,discuss_id:int,msg:bytes) -> int: ...
def deleteMsg(auth_code: int,msg_id:int) -> int: ...

# friend operation
def sendLike(auth_code: int, qq:int) -> int: ...
def sendLikeV2(auth_code: int, qq:int) -> int: ...

# group operation
def setGroupKick(auth_code: int, group_id:int, qq:int, reject_add_request: int) -> int: ...
def setGroupBan(auth_code: int, group_id: int, qq: int, duration: int) -> int: ...
def setGroupAnonymousBan(auth_code: int, group_id: int, anonymous: bytes, duration: int) -> int: ...
def setGroupWholeBan(auth_code: int, group_id: int, enable: int) -> int: ...
def setGroupAdmin(auth_code: int, group_id: int, qq: int, set: int) -> int: ...
def setGroupAnonymous(auth_code: int, group_id: int, enable: int) -> int: ...
def setGroupCard(auth_code: int, group_id: int, qq: int, new_card: bytes) -> int: ...
def setGroupLeave(auth_code: int, group_id: int, is_dismiss: int) -> int: ...
def setGroupSpecialTitle(auth_code: int, group_id: int, qq: int, new_special_title: bytes, duration: int) -> int: ...
def setDiscussLeave(auth_code: int, discuss_id: int) -> int: ...

# request
def setFriendAddRequest(auth_code: int, response_flag: bytes, response_operation: int, remark: bytes) -> int: ...
def setGroupAddRequest(auth_code: int, response_flag: bytes, request_type: int, response_operation: int) -> int: ...
def setGroupAddRequestV2(auth_code: int, response_flag: bytes, request_type: int, response_operation: int, reason: bytes) -> int: ...

# QQ Information
def getLoginQq(auth_code: int) -> int: ...
def getLoginNick(auth_code: int) -> bytes: ...
def getStrangerInfo(auth_code: int, qq: int, no_cache: int) -> bytes: ...
def getFriendList(auth_code: int, reserved: int) -> bytes: ...
def getGroupList(auth_code: int) -> bytes: ...
def getGroupInfo(auth_code: int, group_id: int, no_cache: int) -> bytes: ...
def getGroupMemberList(auth_code: int, group_id: int) -> bytes: ...
def getGroupMemberInfoV2(auth_code: int, group_id: int, qq: int, no_cache: int) -> bytes: ...

# CoolQ
def getCookies(auth_code: int) -> bytes: ...
def getCookiesV2(auth_code: int, domain: bytes) -> bytes: ...
def getCsrfToken(auth_code: int) -> int: ...
def getAppDirectory(auth_code: int) -> bytes: ...
def getRecord(auth_code: int, file: bytes, out_format: bytes) -> bytes: ...
def getRecordV2(auth_code: int, file: bytes, out_format: bytes) -> bytes: ...
def getImage(auth_code: int, file: bytes) -> bytes: ...
def canSendImage(auth_code: int) -> int: ...
def canSendRecord(auth_code: int) -> int: ...
def addLog(auth_code: int, level: int, category: bytes, log_msg: bytes) -> int: ...
def setFatal(auth_code: int, error_info: bytes) -> int: ...
def setRestart(auth_code: int) -> int: ...